fail_fast: true

repos:
  - repo: local
    hooks:
      - id: stylua
        name: stylua
        entry: stylua --check
        language: system
        types: [lua]
      - id: markdown
        name: markdown
        entry: deno fmt --options-line-width 79 --check
        language: system
        types: [markdown]
