return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  -- event = 'BufReadPost',
  lazy = false,
  dependencies = {
    'yioneko/nvim-yati',
    'JoosepAlviste/nvim-ts-context-commentstring',
  },
  config = function()
    require('nvim-treesitter.configs').setup({
      ensure_installed = {
        'bash',
        'c',
        'css',
        'comment',
        'diff',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'git_config',
        -- Needs generation from grammar: 'gitignore',
        'go',
        'gomod',
        'gosum',
        'html',
        'javascript',
        'json',
        'lua',
        'make',
        'markdown',
        'markdown_inline',
        'python',
        'query',
        'regex',
        'rust',
        -- Needs generation from grammar: 'sql',
        'terraform',
        'toml',
        'vim',
        'vimdoc',
        'yaml',
      },
      highlight = { enable = true },
      indent = {
        enable = true,
        -- Disable indent for languages handled by yati:
        disable = {
          'c',
          'cpp',
          'css',
          'html',
          'javascript',
          'json',
          'lua',
          'rust',
          'python',
          'toml',
        },
      },
      yati = { enable = true },
      context_commentstring = { enable = true, enable_autocmd = false },
    })
  end,
}
