return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  -- event = 'BufReadPost',
  lazy = false,
  config = function()
    require('nvim-treesitter.configs').setup({
      ensure_installed = {
        'bash',
        'c',
        'css',
        'comment',
        'diff',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'git_config',
        -- Needs generation from grammar: 'gitignore',
        'go',
        'gomod',
        'gosum',
        'html',
        'javascript',
        'json',
        'lua',
        'make',
        'markdown',
        'markdown_inline',
        'python',
        'query',
        'regex',
        'rust',
        -- Needs generation from grammar: 'sql',
        'terraform',
        'toml',
        'vim',
        'vimdoc',
        'yaml',
      },
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
