name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v2
      with:
        # Required to download stylua binary:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Check markdown format
      run: find . -name \*.md | xargs deno fmt --options-line-width 79 --check
